spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL} # 실제 연결 운영 DB URL 추가 필요(secrets, env 변수 등)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 validate만 사용
    show-sql: false  # 운영에서는 SQL 로그 비활성화

logging:
  level:
    org.hibernate.SQL: WARN # hibernate 내부 로그도 warn 이상만
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN
    com.back.api.aspect.PerformanceMonitoringAspect: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never