spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/waitfair
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

security:
  password:
    bcrypt-strength: 4

sms:
  test:
    enabled: true        # 고정 인증번호 활성화
    fixed-code: "123456" # HTTP 파일에서 123456 사용