spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 validate만 사용
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
      show-sql: false # 이거 없으면 aws 세션에서 확인할 때 쿼리 로그 뜸

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

# 운영 환경용 로깅 설정
logging:
  level:
    root: INFO
    com.back: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN

# custom.site 설정을 prod로 오버라이드
custom:
  site:
    domain: "${custom.prod.domain}"
    back-url: "${custom.prod.back-url}"
    front-url: "${custom.prod.front-url}"

  cors:
    allowed-origins:
      - ${FRONTEND_URL}
      - ${BACKEND_URL}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - "*"

# Actuator 설정 (최소한의 엔드포인트만 노출)
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never

sms:
  coolsms:
    api-key: ${COOLSMS_API_KEY}
    api-secret: ${COOLSMS_API_SECRET}
    from-number: ${COOLSMS_FROM_NUMBER}