spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SUPABASE_URL}
    username: ${SUPABASE_USERNAME}
    password: ${SUPABASE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        prepareThreshold: 0
        cachePrepStmts: false
        useServerPrepStmts: false

  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 validate만 사용
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
      show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

# 운영 환경용 로깅 설정
logging:
  level:
    root: INFO
    com.back: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN

# custom.site 설정을 prod로 오버라이드
custom:
  site:
    domain: "${custom.prod.domain}"
    back-url: "${custom.prod.back-url}"
    front-url: "${custom.prod.front-url}"

  cors:
    allowed-origins:
      - ${FRONTEND_URL}
      - ${BACKEND_URL}
      - http://localhost:3000
      - http://localhost:5173 # 프론트 배포 후 제거

# Actuator 설정 (최소한의 엔드포인트만 노출)
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never

# TODO: 프론트 완료 후 아래 주석처리 한 걸로 교체
cookie:
  secure: true
  same-site: None
  domain: ""

#cookie:
#  secure: true
#  same-site: None
#  domain: ".waitfair.shop"

# 임시 운영환경용 스케줄러. redis 해결 후 삭제
queue:
  scheduler:
    #입장 처리 스케줄러
    entry:
      cron: "0 0 3 * * *"  # 매일 새벽 3시
      batch-size: 100
      max-entered-limit: 100
    shuffle:
      cron: "0 0 4 * * *"  # 매일 새벽 4시
      time-range-minutes: 1
    expire:
      cron: "0 0 5 * * *"  # 매일 새벽 5시

event:
  scheduler:
    open:
      cron: "0 0 2 * * *"  # 매일 새벽 2시

# coolSMS
sms:
  coolsms:
    api-key: ${COOLSMS_API_KEY}
    api-secret: ${COOLSMS_API_SECRET}
    from-number: ${COOLSMS_FROM_NUMBER}
  test:
    enabled: false